@port = 3000
@host = http://localhost:{{port}}


### /register
GET {{host}}/api/register

### /login
GET {{host}}/api/login

### /personal_data
GET {{host}}/api/personal_data

### /experience
GET {{host}}/api/experience

### /training
GET {{host}}/api/training

### /projects
GET {{host}}/api/projects

### /resume
GET {{host}}/api/resume
